SIEXIT.labMk2RecipeName = SIGen.NewRecipe( SIEXIT.labMk2Name )
.SetEnergy( 5 )
.SetRecipeTypes( "crafting" )
.AddCosts( "lab" , 2 )
.AddCosts( "fast-transport-belt" , 6 )
.AddCosts( "fast-splitter" , 1 )
.AddCosts( "advanced-circuit" , 4 )
.SetResults( SIEXIT.labMk2ItemName )
.GetCurrentEntityName()

SIEXIT.labMk3RecipeName = SIGen.NewRecipe( SIEXIT.labMk3Name )
.SetEnergy( 25 )
.SetRecipeTypes( "crafting" )
.AddCosts( SIEXIT.labMk2ItemName , 2 )
.AddCosts( "express-transport-belt" , 10 )
.AddCosts( "express-splitter" , 2 )
.AddCosts( "processing-unit" , 6 )
.AddCosts( "low-density-structure" , 5 )
.SetResults( SIEXIT.labMk3ItemName )
.GetCurrentEntityName()

SIEXIT.sciencePackRecipeName = SIGen.NewRecipe( SIEXIT.sciencePackName )
.SetEnergy( 40 )
.SetRecipeTypes( "crafting" )
.AddCosts( "burner-mining-drill" , 5 )
.AddCosts( "burner-inserter" , 5 )
.AddCosts( "steel-furnace" , 10 )
.AddCosts( "effectivity-module-3" , 2 )
.AddCosts( "atomic-bomb" , 3 )
.AddCosts( "modular-armor" , 2 )
.SetResults( SIEXIT.sciencePackName , 29 )
.GetCurrentEntityName()